# Compile the project as waebassembly and upload the generated
# file and the html and js in static to the repo containing the blog: https://github.com/tsoobame/tsoobame.github.io/tree/main
name: Publish p5
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "p5/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "18.17"

      - name: Build and publish js
        run: |
          cd p5
          npm install
          npm run build

      - name: Push to tsoobame repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "p5/dist"
          destination-github-username: "tsoobame"
          destination-repository-name: "tsoobame.github.io"
          target-directory: "demos/procedural-animations-p5"
          user-email: ${{ secrets.SSH_KEY_EMAIL }}
          target-branch: main
